### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by jcc10** [yawkat/FimFiction-Android#1]
I am getting a unknown error when trying to log in. The error happens after I hit login and after the loading icon.

Please help!

Wwjdtd.

**Comment by SaphireLattice** [comment]
Can confirm that it happens for me too. Not really a lot of information expect that it says "Unknown error". Tried to use both username and email, with or without "remember" flag checked. And by the looks of it it happens regardless of correct/incorrect password.

**Comment by yawkat** [comment]
Can you provide the logs from /storage/emultated/0/FimFiction/logs ?

**Comment by jcc10** [comment]
2015-05-26 11:57:17,188 -
[DEBUG::at.yawk.fimfiction.android.TaskManager::at.yawk.fimfiction.android.TaskManager]
- Removing invalid task at.yawk.fimfiction.android.Task@425b5778 from task
  queue (3 remaining)
  2015-05-26 11:57:17,198 -
  [DEBUG::at.yawk.fimfiction.android.TaskManager::at.yawk.fimfiction.android.TaskManager]
- Removing invalid task at.yawk.fimfiction.android.Task@426b6c80 from task
  queue (2 remaining)
  2015-05-26 11:57:17,202 -
  [DEBUG::at.yawk.fimfiction.android.TaskManager::at.yawk.fimfiction.android.TaskManager]
- Removing invalid task at.yawk.fimfiction.android.Task@42687730 from task
  queue (1 remaining)
  2015-05-26 11:57:35,725 -
  [DEBUG::at.yawk.fimfiction.android.TaskManager::at.yawk.fimfiction.android.TaskManager]
- Removing invalid task at.yawk.fimfiction.android.Task@42570748 from task
  queue (2 remaining)
  2015-05-26 11:57:35,729 -
  [DEBUG::at.yawk.fimfiction.android.TaskManager::at.yawk.fimfiction.android.TaskManager]
- Removing invalid task at.yawk.fimfiction.android.Task@42504378 from task
  queue (1 remaining)

**Comment by SaphireLattice** [comment]
Somewhy in last build there is no such messages (well, as "last" as january
build can get).

2014-05-16 19:44:22,400 -
[INFO::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker]
- Changing parameters to SearchParameters{unread="true",
  order="UPDATE_DATE", favorited="true"}
  2014-05-16 19:44:22,445 -
  [DEBUG::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker]
- Updating display (done=false, content.length=0)
  2014-05-16 19:44:22,454 -
  [DEBUG::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker]
- Updating display (done=false, content.length=0)
  2014-05-16 19:44:25,690 -
  [DEBUG::at.yawk.fimfiction.android.SearchView::at.yawk.fimfiction.android.SearchView]
- Loaded data on page 0 (0 0)
  2014-05-16 19:44:25,705 -
  [DEBUG::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker$WorkerSession]
- No more data!
  2014-05-16 19:44:25,709 -
  [DEBUG::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker]
- Updating display (done=true, content.length=0)
  2014-05-16 19:44:33,168 -
  [DEBUG::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker$WorkerSession]
- We got interrupted, aborting!
  2014-05-16 19:44:33,173 -
  [DEBUG::at.yawk.fimfiction.android.TaskManager::at.yawk.fimfiction.android.TaskManager]
- Removing invalid task at.yawk.fimfiction.android.Task@4198fa40 from task
  queue (1 remaining)
  2014-05-16 19:44:34,146 -
  [INFO::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker]
- Changing parameters to SearchParameters{unread="true",
  order="UPDATE_DATE", favorited="true"}
  2014-05-16 19:44:34,176 -
  [DEBUG::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker]
- Updating display (done=false, content.length=0)
  2014-05-16 19:44:34,179 -
  [DEBUG::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker]
- Updating display (done=false, content.length=0)
  2014-05-16 19:44:35,766 -
  [DEBUG::at.yawk.fimfiction.android.SearchView::at.yawk.fimfiction.android.SearchView]
- Loaded data on page 0 (0 0)
  2014-05-16 19:44:35,777 -
  [DEBUG::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker$WorkerSession]
- No more data!
  2014-05-16 19:44:35,780 -
  [DEBUG::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker]
- Updating display (done=true, content.length=0)
  2014-07-07 18:28:40,702 -
  [DEBUG::at.yawk.fimfiction.android.TaskManager::at.yawk.fimfiction.android.TaskManager]
- Removing invalid task at.yawk.fimfiction.android.Task@42085c80 from task
  queue (1 remaining)
  2014-07-15 23:35:10,693 -
  [INFO::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker]
- Changing parameters to SearchParameters{unread="true",
  order="UPDATE_DATE", favorited="true"}
  2014-07-15 23:35:10,733 -
  [DEBUG::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker]
- Updating display (done=false, content.length=0)
  2014-07-15 23:35:10,737 -
  [DEBUG::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker]
- Updating display (done=false, content.length=0)
  2014-07-15 23:35:13,789 -
  [DEBUG::at.yawk.fimfiction.android.SearchView::at.yawk.fimfiction.android.SearchView]
- Loaded data on page 0 (0 0)
  2014-07-15 23:35:13,806 -
  [DEBUG::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker$WorkerSession]
- No more data!
  2014-07-15 23:35:13,811 -
  [DEBUG::at.yawk.fimfiction.android.StoryListWorker::at.yawk.fimfiction.android.StoryListWorker]
- Updating display (done=true, content.length=0)
  2014-08-02 20:30:33,167 -
  [DEBUG::at.yawk.fimfiction.android.TaskManager::at.yawk.fimfiction.android.TaskManager]
- Removing invalid task at.yawk.fimfiction.android.Task@42e1fae8 from task
  queue (1 remaining)
  2015-05-25 10:00:01,917 -
  [DEBUG::at.yawk.fimfiction.android.TaskManager::at.yawk.fimfiction.android.TaskManager]
- Removing invalid task at.yawk.fimfiction.android.Task@42053a20 from task
  queue (1 remaining)
  And no, the "Unknown error" didn't wanished.like debug message

**Comment by SaphireLattice** [comment]
Any progress or info on that?

**Comment by yawkat** [comment]
This project is now deprecated and has been replaced by https://github.com/yawkat/fiction-android in an effort to simplify future maintanance as the site evolves.
